# general settings
name: HyperThumbnail_4x_f24_2e-2
model_type: HyperThumbnail_Model
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/demo_dataset/kodak/GTmod12
    dataroot_lq: datasets/demo_dataset/kodak/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/demo_dataset/Set5/GTmod12
    dataroot_lq: datasets/demo_dataset/Set5/LRbicx4
    io_backend:
      type: disk
    crop_val: true

# network structures
network_g:
  type: HyperThumbnail
  scale: 4
  patch_size: 256
  norm: none
  quant_type: bypass
  predict_quant_table: true
  pool_type: avg
  chroma_sub: false
  is_train: true

  decoder_opt:
    num_in_ch: 27
    num_out_ch: 3
    num_feat: 24
    num_block: 16
    upscale: 4
    res_scale: 1
    img_range: 1.0
    rgb_mean: [0.4488, 0.4371, 0.4040]    
    input_norm: False

  coe_decoder_opt:
    num_in_ch: 192
    num_out_ch: 24
    num_feat: 24
    num_block: 16
    upscale: 8
    res_scale: 1
    out_range: 10.0
    mean: None

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  fix_and_grad:
    fix: ['Y_TABLE', 'C_TABLE']
    grad: []

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  
  optim_aux:
    type: Adam
    lr: !!float 2e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: 100000
    gamma: 0.75 

  total_iter: 1800000
  warmup_iter: -1  # no warm up
  gradient_clipping: 5
  bpp_cal_freq: 16

  # losses
  pixel_opt_degrade_lr:
    type: MSELoss
    loss_weight: 0.6
    reduction: mean

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  entropy_opt:
    loss_weight: !!float 2e-2

  # perceptual_opt:
  #   type: PerceptualLoss
  #   layer_weights:
  #     'conv5_4': 1  # before relu
  #   vgg_type: vgg19
  #   use_input_norm: true
  #   range_norm: false
  #   perceptual_weight: 0.8
  #   style_weight: 0
  #   criterion: l1


# validation settings
val:
  val_freq: !!float 5e3
  save_img: true
  val_scaled_lq: true
  val_scaled_degrad_lq: true
  patch_mod: 256
  

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
    lpips_rgb: # metric name, can be arbitrary
      type: calculate_lpips
      crop_border: 2
      test_y_channel: False
    lpips_y: # metric name, can be arbitrary
      type: calculate_lpips
      crop_border: 2
      test_y_channel: True

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
